[package]
name = "ardan_2023_07_24_live"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "day1/hello_world",
    "day1/ownership_move",
    "day1/dropping",
    "day1/cloning",
    "day1/borrowing",
]