[package]
name = "ardan_2023_07_24_live"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "day1/hello_world",
    "day1/ownership_move",
    "day1/dropping",
    "day1/cloning",
    "day1/borrowing",
    "day1/borrow_lifetimes",
    "day1/copyable",
    "day1/reference_count",
    "day1/atomic_reference_count",
    "day1/mutable_shared",
    "day1/mutable_shared_atomic",
    "day1/mutable_sharing_mutex",
    "day1/mutable_sharing_rwlock",
]